# Generated by Django 4.2.6 on 2023-10-25 08:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("infrastructure", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_verify",
            new_name="is_verified",
        ),
    ]
